version: '3.9'

name: "groupsapi"
services:
  web:
    build: .
    command: bash -c "alembic upgrade head && gunicorn -b 0.0.0.0:8000 groupsapi:app"
    env_file:
      - web.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 2s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
