"""Soft delete user

Revision ID: 46a3eb685a56
Revises: 669ce039eb90
Create Date: 2023-07-24 11:43:19.951926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a3eb685a56'
down_revision = '669ce039eb90'
branch_labels = None
depends_on = None


def upgrade(engine_name: str) -> None:
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name: str) -> None:
    globals()["downgrade_%s" % engine_name]()





def upgrade_dev() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deletion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_dev() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deletion_date')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###


def upgrade_test() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deletion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_test() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deletion_date')
    op.drop_column('user', 'is_deleted')
    # ### end Alembic commands ###

